spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接为服务器
    url: jdbc:mysql://60.205.206.201:****/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: ***
    password: ***
  jpa:
    hibernate:
      # 实体类更改数据库表结构也会相应更改，生产环境实体变动数据库不变动
      ddl-auto: none
    show-sql: false
  redis:
    host: 60.205.206.201
    port: 6379
    password: ***

# 日志级别
logging:
  level:
    # 将日志级别升高
    root: off
    # 自定义的日志级别为 debug
    com.mao: off
  # 日志文件路径
  file:
    name: log/blog-pro.log

server:
  port: 8081
