spring:
  profiles:
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    open-in-view: true
  redis:
    port: 6379
    host: 127.0.0.1
# 定义回复头像
comment.avatar: /images/avatar.png

me.github: https://github.com/lloam