spring:
  profiles:
    active: pro
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    open-in-view: true
# 定义回复头像
comment.avatar: /images/avatar.png

me.github: https://github.com/lloam